from .arquivo.arquivo import Arquivos
from .baixar.baixar import Baixar
from .convert.convert import Convert
from .cores.conf_colors import *
from .cores.cores import Cores
from .debug.debug import Debug
from .decode.conf_decode import *
from .decode.decode import Decode
from .encode.conf_encode import *
from .encode.encode import Encode
from .hash_encode.hash_encode import Hash_encode
